
### MAKEMAKE STARTS HERE #######################################################


### Created by makemake.pl on Fri Apr  6 18:15:50 2007 #########################


### GLOBAL TARGETS #############################################################

default: all

re: rebuild

li: link

all: 

clean: 

rebuild: 

link: 

### GLOBAL (AND USER) DEFS #####################################################


AR = ar rv
CC = g++
CCFLAGS =  -I../../flews-0.3/
LD = g++
LDFLAGS =  -framework AGL -framework OpenGL -framework Carbon -framework ApplicationServices -framework vecLib -lm -lmx -lgsl -lblitz -lfltk -lfltk_gl -L../../flews-0.3 -lflews
MKDIR = mkdir -p
RANLIB = ranlib
RMDIR = rm -rf
RMFILE = rm -f
SRC = *.c *.cpp *.cc *.cxx


### MAKEMAKE ENDS HERE #########################################################

